[features]
seeds = false
[programs.localnet]
rent = "2QofFxHF1vPYKp6hUhi83iZpwLfXSKZsb1QKZwZoDSR8"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/truongnx/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
